src/BdE/WeiBundle/Entity/Bungalow.php
<?php

namespace BdE\WeiBundle\Entity;

use BdE\WeiBundle\Utils\Affectation;
use Cva\GestionMembreBundle\Entity\Etudiant;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Bungalow
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="BungalowRepository")
 */
class Bungalow
{
    const BOYS = "M";
    const GIRLS = "F";
    const NOT_DETERMINED = "ND";

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=255)
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="sexe", type="string", length=2, nullable=true)
     * @Assert\Choice(choices = {"M", "F", "ND"}, message = "La valeur doit être M, F ou ND")
     */
    private $sexe;

    /**
     * @var integer
     *
     * @ORM\Column(name="nbPlaces", type="integer")
     */
    private $nbPlaces;

    /**
     * Describe Etudiants who are affected in a Bungalow for the WEI
     *
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Cva\GestionMembreBundle\Entity\Etudiant", mappedBy="bungalow")
     *
     * @ORM\JoinTable(
     *      name="etudiants_bungalow",
     *      joinColumns={@ORM\JoinColumn(name="bungalow_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="etudiant_id", referencedColumnName="id", unique = true)}
     * )
     */
    private $students;

    /**
     * Designate the bus from which students comes.
     *
     * @var Bus
     * @ORM\ManyToOne(targetEntity="BdE\WeiBundle\Entity\Bus", inversedBy="bungalows")
     * @ORM\JoinColumn(nullable=true)
     */
    private $bus;

    /**
     * Bus constructor.
     */
    public function __construct()
    {
        $this->students = new ArrayCollection();
    }

    /**
     * @return Bus
     */
    public function getBus()
    {
        return $this->bus;
    }

    /**
     * @param Bus $bus
     * @return Bungalow
     */
    public function setBus($bus)
    {
        $this->bus = $bus;
        return $this;
    }

    public static function getSexChoices()
    {
        return [
            self::BOYS => "Mens",
            self::GIRLS => "Womens",
            self::NOT_DETERMINED => "Mixed"
        ];
    }

    public function __toString()
    {
        return $this->nom;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nom
     *
     * @param string $nom
     * @return Bungalow
     */
    public function setNom($nom)
    {
        $this->nom = $nom;
    
        return $this;
    }

    /**
     * Get nom
     *
     * @return string 
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set sexe
     *
     * @param string $sexe
     * @return Bungalow
     */
    public function setSexe($sexe)
    {
        $this->sexe = $sexe;
    
        return $this;
    }

    /**
     * Get sexe
     *
     * @return string 
     */
    public function getSexe()
    {
        return $this->sexe;
    }

    public function getHumanReadableSexe(){
        switch($this->sexe){
            case 'F':
                return "Filles";
            case 'M':
                return "Garçons";
            default:
                return "Mixte";
        }
    }

    /**
     * Set nbPlaces
     *
     * @param integer $nbPlaces
     * @return Bungalow
     */
    public function setNbPlaces($nbPlaces)
    {
        $this->nbPlaces = $nbPlaces;
    
        return $this;
    }

    /**
     * Get nbPlaces
     *
     * @return integer 
     */
    public function getNbPlaces()
    {
        return $this->nbPlaces;
    }


    /**
     * Fetch all Etudiants registred on this bungalow.
     * @return array A copy of the ArrayCollection of Etudiants.
     */
    public function getStudents(){
        return $this->students->toArray();
    }

    /**
     * Add an Etudiant to this bungalow
     * @param Etudiant $student The person to add
     * @return Affectation Result from this, see BdE\WeiBundle\Utils\Affectation
     */
    public function addStudent(Etudiant $student){
        if(!$student) return Affectation::Error;
        if($this->students->contains($student)) return Affectation::AlreadyIn;
        if($student->hasBungalow()) return Affectation::AffectedToAnother;
        if($this->getNbPlaces()>=$this->getAmountOfRegisteredEtudiants()) return Affectation::Full;
        $this->students->add($student);
        return Affectation::OK;
    }

    /**
     * Remove an Etudiant from this bungalow
     * @param Etudiant $student The person to add
     * @return Affectation Result from this, see BdE\WeiBundle\Utils\Affectation
     */
    public function removeStudent(Etudiant $student){
        if(!$student) return Affectation::Error;
        if(!$this->students->contains($student)) return Affectation::Error;
        $this->students->remove($student);
        return Affectation::OK;
    }

    /**
     * Count numbers of Etudiant registered in this bungalow.
     * @return integer Amount of registered Etudiants
     */
    public function getAmountOfRegisteredEtudiants(){
        return $this->students->count();
    }

    /**
     * Determines if it can be deleted.
     *
     * @return boolean True if it could be deleted safely
     */
    public function canBeDeletedSafely(){
        return $this->getAmountOfRegisteredEtudiants() <= 0; // Inferior to 0 will be strange but we doesn't let as
        // a functional bug
    }

    public function removeStudents()
    {
        $this->students = new ArrayCollection();
    }

}

src/BdE/WeiBundle/Form/BungalowType.php
<?php
namespace BdE\WeiBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class BungalowType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
		->add('nom', 'text', array('required' => true))
        ->add('sexe', 'choice', array('choices' => array('F' => 'Filles','M' => 'Garçons', "ND" =>'Mixte'),'required'  => false, 'expanded' => false,'empty_value' => false ))
		->add('bus', 'entity', array('class'=> 'BdE\WeiBundle\Entity\Bus','required'=>false))
            ->add('nbPlaces', 'integer', array('required' => true))
            ->add('actions', 'form_actions', [
                'buttons' => [
                    'save' => ['type' => 'submit', 'options' => ['label' => 'button.save']],
                    'cancel' => ['type' => 'reset', 'options' => ['label' => 'button.cancel','attr' => ['onclick'=>"history.back()"]]],
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array('data_class' => 'BdE\WeiBundle\Entity\Bungalow'));
        //$resolver->setRequired('bus');
    }

    public function getName()
    {
        return 'bungalow';
    }
}

src/BdE/WeiBundle/Controller/BungalowController.php
<?php

namespace BdE\WeiBundle\Controller;

use BdE\WeiBundle\Entity\Bungalow;
use BdE\WeiBundle\Form\BungalowType;
use Cva\GestionMembreBundle\Entity\Etudiant;
use Doctrine\ORM\NoResultException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class BungalowController extends Controller
{

    /**
     * @Route("/",name="bde_wei_bungalow")
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function indexAction(){
        // Load data
        $em = $this->getDoctrine()->getManager();
        $bungalows = $em->getRepository("BdEWeiBundle:Bungalow")->findAll();
        return $this->render("@BdEWei/Bungalow/index.html.twig",array('bungalows'=>$bungalows));
    }

    /**
    * @Route("/assign",name="bde_wei_bungalow_assign")
    * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
    */
    public function assignAction(){
        $em = $this->getDoctrine()->getManager();
        $weiProduct = $em->getRepository("CvaGestionMembreBundle:Produit")->getCurrentWEI();
        $students = $em->getRepository("CvaGestionMembreBundle:Etudiant")->createQueryBuilder('etudiant')
            ->leftJoin('etudiant.payments','payment')->where('payment.product = ?1')
            ->setParameter(1, $weiProduct)->getQuery()->getResult();
        $bungalowsWithBus = $em->getRepository("BdEWeiBundle:Bungalow")->createQueryBuilder('bungalow')
            ->where('bungalow.bus IS NOT NULL')
            ->having('bungalow.nbPlaces > COUNT(etudiants.id)')
            ->leftJoin('bungalow.students','etudiants')
            ->groupBy('bungalow.id')
            ->getQuery()->getResult();
        $bungalowsWithoutBus = $em->getRepository("BdEWeiBundle:Bungalow")->createQueryBuilder('bungalow')
            ->where('bungalow.bus IS NULL')
            ->having('bungalow.nbPlaces > COUNT(etudiants.id)')
            ->leftJoin('bungalow.students','etudiants')
            ->groupBy('bungalow.id')
            ->getQuery()->getResult();
        $fuller = array();
        /** @var Bungalow $bungalow */
        foreach(array_merge($bungalowsWithBus,$bungalowsWithoutBus) as $bungalow){
            $fuller[$bungalow->getId()] = $bungalow->getAmountOfRegisteredEtudiants();
        }
        /** @var Etudiant $student */
        foreach ($students as $student) {
            if($student->getBungalow())
                break;
            /** @var Bungalow $bungalow */
            foreach($bungalowsWithBus as $key => $bungalow){

                if($fuller[$bungalow->getId()] >= $bungalow->getNbPlaces()) {
                    unset($bungalowsWithBus[$key]);
                    continue;
                }

                if($bungalow->getSexe() == Bungalow::NOT_DETERMINED OR $bungalow->getSexe() == ($student->getCivilite()=='M'?Bungalow::BOYS:Bungalow::GIRLS)){
                    if($bungalow->getBus() == $student->getBus()){
                        $fuller[$bungalow->getId()]++;
                        $student->setBungalow($bungalow);
                        $bungalow->addStudent($student);
                        break;
                    }
                }
            }
            if($student->getBungalow() == null){
                foreach($bungalowsWithoutBus as $key => $bungalow){

                    if($fuller[$bungalow->getId()] >=  $bungalow->getNbPlaces()) {
                        unset($bungalowsWithoutBus[$key]);
                        continue;
                    }

                    if($bungalow->getSexe() == Bungalow::NOT_DETERMINED OR $bungalow->getSexe() == ($student->getCivilite()=='M'?Bungalow::BOYS:Bungalow::GIRLS)){
                        $fuller[$bungalow->getId()]++;
                        $student->setBungalow($bungalow);
                        $bungalow->addStudent($student);
                        break;
                    }
                }
            }
            $em->persist($student);
        }
        $em->flush();
        return $this->redirectToRoute("bde_wei_bungalow");
    }

    /**
    * @Route("/unassign",name="bde_wei_bungalow_unassign")
    * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
    */
    public function unassignAction(){
        // Load data
        $em = $this->getDoctrine()->getManager();
        $bungalows = $em->getRepository("BdEWeiBundle:Bungalow")->findAll();
        foreach ($bungalows as $bungalow) {
            /** @var Etudiant $student */
            foreach($bungalow->getStudents() as $student){
                $student->setBungalow(null);
            }
            $em->persist($bungalow);
        }
        $em->flush();
        $this->addFlash('success', "Les étudiants ont été viré des bungalow !");
        return $this->redirectToRoute("bde_wei_bungalow");
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @Route(path="/addMany",name="bde_wei_bungalow_add_many")
     * @Method({"GET","POST"})
     */
    public function addManyAction(Request $request)
    {
        // Get data from Form
        // The way to use a get from the request is bad but on one side you can't use symfony form on GET request
        // And on the other way you can't put it as url param because it comes from a form and JS is bad !
        $amount = $this->getRequest()->get("nbBung");

        $em = $this->getDoctrine()->getManager();
        $nbBung = $amount;

        if($amount <= 0){
            throw new \InvalidArgumentException("Amount of bungalow can not be less than 1");
        }

        for ($i = 0; $i < $nbBung; $i++) {
            $bungalow = new Bungalow();
            $bungalow->setNom("Bung ".$i);
            $bungalow->setNbPlaces(6);

            $em->persist($bungalow);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('cva_gestion_membre_config'));
    }

    /**
     * @Route("/add",name="bde_wei_bungalow_add")
     * @Method({"POST"})
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function createAction(){
        // Load data
        $em = $this->getDoctrine()->getManager();
        $form = $this->createForm(new BungalowType(), new Bungalow());

        // Handle the form
        $form->handleRequest($this->getRequest());

        // If valid, we act
        if($form->isSubmitted() && $form->isValid()){
            $em->persist($form->getData());
            $em->flush();
            $this->get('session')->getFlashBag()->add('notice', 'Bungalow ajouté');
            return $this->redirect($this->generateUrl('cva_gestion_membre_config'));
        } else { // Else, recreate the page
            return $this->forward("BdEWeiBundle:Bungalow:new");
        }
    }

    /**
     * @Route("/add",name="bde_wei_bungalow_add")
     * @Method({"GET"})
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function newAction(Request $request)
    {
        $bungalow = new Bungalow();
        $form = $this->createForm(new BungalowType(), $bungalow);
        $em = $this->getDoctrine()->getManager();

        $form->handleRequest($request);

        if($form->isValid()){
            $em->persist($form->getData());
            $em->flush();
            $this->addFlash('success',"Nouveau bungalow enregistré");
            return $this->redirectToRoute("bde_wei_bungalow");
        }

        return $this->render('BdEWeiBundle:Bungalow:add.html.twig', array('form' => $form->createView(),));
    }

    /**
     * @Route("/{id}", requirements={"id" = "\d+"},name="bde_wei_bungalow_edit")
     * @Method({"GET","POST"})
     * @param Request $request
     * @param $id mixed Params for request which describe id of bus
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function editAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();
        $bungalow = $em->getRepository("BdEWeiBundle:Bungalow")->find($id);

        if(!$bungalow){
            throw $this->createNotFoundException("Bungalow with id [".htmlentities($id)."] is not found");
        }

        $form = $this->createForm(new BungalowType(), $bungalow);

        $form->handleRequest($request);
        if ($form->isValid())
        {
            $em->persist($form->getData());
            $em->flush();
            $this->get('session')->getFlashBag()->add('success', 'Bungalow modifié');
            return $this->redirect($this->generateUrl('bde_wei_bungalow'));
        }

        return $this->render('BdEWeiBundle:Bungalow:edit.html.twig', array('form' => $form->createView()));
    }

    /**
     * @Route("/{id}/delete", requirements={"id" = "\d+"},name="bde_wei_bungalow_delete")
     * @Method({"GET","DELETE"})
     * @param mixed $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function deleteAction($id) {

        $em = $this->getDoctrine()->getManager();
        $bungalow = $em->getRepository("BdEWeiBundle:Bungalow")->find($id);

        if($bungalow->canBeDeletedSafely()){
            $this->get('session')->getFlashBag()->add('warning', 'Ce bungalow n\'est pas vide !');
            return $this->redirect($this->generateUrl('cva_gestion_membre_config'));
        }

        $em->remove($bungalow);
        $em->flush();

        $this->get('session')->getFlashBag()->add('notice', 'Bung supprimé');
        return $this->redirect($this->generateUrl('cva_gestion_membre_config'));
    }

}

src/BdE/WeiBundle/Resources/views/Bungalow/add.html.twig
{% extends '@BdEWei/Bungalow/edit.html.twig' %}

{% block head_title %}Ajouter un bungalow{% endblock %}

src/BdE/WeiBundle/Resources/views/Bungalow/edit.html.twig
{% extends '::base.html.twig' %}

{% block content  %}
	<div class="container">
		{{ form_start(form, { 'style': 'horizontal' }) }}
		<div class="page-header">
			<h1>{% block head_title %}Editer un bungalow{% endblock %}
				<div class="btn-group pull-right" style="">
					{{ form_widget(form.actions) }}
				</div>
			</h1>
		</div>
		{{ form(form, { 'style': 'horizontal' }) }}
		{{ form_end(form) }}
		<h3>Liste des étudiants dans ce bungalow</h3>
		{% if form.vars.value.students | length > 0%}
		<ul>
			{% for student in form.vars.value.students %}
			<li>{{ student }}</li>
			{% endfor %}
		</ul>
		{% else %}
		Aucun étudiant affecté
		{% endif %}
	</div>
{% endblock %}

src/BdE/WeiBundle/Resources/views/Bungalow/index.html.twig
{% extends '::base.html.twig' %}

{% block content  %}
	<div class="container">
		<div class="page-header">
			<h1>Bungalows
				<div class="pull-right">
					<div class="btn-group" style="">
						<a class="btn btn-primary" href="{{ url("bde_wei_bungalow_assign") }}">{{ icon('refresh') }} Affecter les étudiants</a>
						<a class="btn btn-danger" data-toggle="modal" data-target="#confirm-unasign" href="#" data-href="{{ url("bde_wei_bungalow_unassign") }}">{{ icon('trash') }} Effacer les affectations</a>
						<a class="btn btn-success" href="{{ url("bde_wei_bungalow_add") }}">{{ icon('plus') }}</a>
					</div>
				</div>
			</h1>
		</div>
		<div class="row">
			<div class="col-md-12">
				<table id="table_bungalow" class="table table-bordered table-hover table-striped">
					<thead>
					<tr id="search">
						<th>ID</th>
						<th>Nom</th>
						<th>Type</th>
						<th>Bus</th>
						<th>Remplissage</th>
						<th width="107px"></th>
					</tr>
					</thead>
					<tbody id="bungalows">
					{% for bungalow in bungalows %}
						<tr>
							<td>{{ bungalow.id }}</td>
							<td>{{ bungalow.nom }}</td>
							<td>{{ bungalow.humanReadableSexe }}</td>
							<td>{{ bungalow.bus | default('Aucun bus affecté') }}</td>
							<td>
								<div class="progress">
									<div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: {{ 100*bungalow.amountOfRegisteredEtudiants/bungalow.nbPlaces | number_format }}%;">

									</div>
								</div>
								<div class="text-center">{{ bungalow.amountOfRegisteredEtudiants }} sur {{ bungalow.nbPlaces }}</div>
							</td>
							<td>
								<div class="btn-group">
									<a href="{{ url("bde_wei_bungalow_edit",{id:bungalow.id}) }}" class="btn btn-default">
										{{ icon("pencil") }}
									</a>
									<a href="#" data-toggle="modal" data-target="#confirm-delete" data-href="{{ url("bde_wei_bungalow_delete",{id:bungalow.id}) }}" class="btn btn-danger">
										{{ icon("trash") }}
									</a>
								</div>
							</td>
						</tr>
					{% endfor %}
					</tbody>
				</table>
			</div>

		</div>

	</div>

	<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content panel-danger">
				<div class="modal-header panel-heading">
					Zone de danger
				</div>
				<div class="modal-body">
					Voulez-vous supprimer ce bungalow ?
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
					<a class="btn btn-danger btn-ok">Delete</a>
				</div>
			</div>
		</div>
		<script>
		</script>
	</div>
	<div class="modal fade" id="confirm-unasign" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					Zone de Danger !
				</div>
				<div class="modal-body">
					Voulez-vous supprimer l'affectation des étudiants dans les bungalow ?
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Non</button>
					<a class="btn btn-danger btn-ok" href="{{ url("bde_wei_bungalow_unassign") }}">Oui</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{% block javascripts %}

	<script src="https://cdn.datatables.net/1.10.8/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.8/js/dataTables.bootstrap.min.js"></script>
	<script>
		$(function () {
			$('#confirm-delete').on('show.bs.modal', function(e) {
				$(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));
			});
		});
		$(function(){

			var TableAssemblees = $('#table_bungalow').dataTable({
				"oLanguage": {
					"sProcessing":     "Traitement en cours...",
					"sSearch":         "Rechercher&nbsp;:&nbsp;",
					"sInfo":           "Affichage des &eacute;l&eacute;ments _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
					"sInfoEmpty":      "Aucun &eacute;l&eacute;ment &agrave; afficher",
					"sInfoFiltered":   "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
					"sInfoPostFix":    "",
					"sLoadingRecords": "Chargement en cours...",
					"sLengthMenu":     "Afficher _MENU_ &eacute;l&eacute;ments",
					"sZeroRecords":    "Aucun r&eacute;sultat ne correspond à votre recherche.",
					"sEmptyTable":     "Aucune donnée disponible dans le tableau",
					"oPaginate": {
						"sFirst":      "Premier",
						"sPrevious":   "Pr&eacute;c&eacute;dent",
						"sNext":       "&nbsp;Suivant",
						"sLast":       "Dernier"
					},
					"oAria": {
						"sSortAscending":  ": activer pour trier la colonne par ordre croissant",
						"sSortDescending": ": activer pour trier la colonne par ordre décroissant"
					}
				}
			});
		})
	</script>
	<style>
		.dataTables_filter{
			float: right !important;
		}
		.dataTables_filter:after{
			clear: both;
		}
	</style>

{% endblock %}